
services:
  postgres:
    image: postgres:15-alpine
    container_name: github_wrapped_db
    environment:
      POSTGRES_USER: data_engineer
      POSTGRES_PASSWORD: my_secret_password
      POSTGRES_DB: github_wrapped 
    ports: 
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data 
  app:
    build: .
    container_name: wrapped_app
    depends_on:
      - postgres
    # Pass the entire .env file directly into your Python container
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
volumes:
  pgdata: 